name: WDX
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pip
  - pip:
      - attrs==24.2.0
      - minknow-api==5.7.2
      - pod5==0.3.15
      - vbz-h5py-plugin==1.0.1
  - dtaidistance=2.3.11
  - scikit-learn=1.3.1
  - scipy=1.10.1
  - cython=0.29.36
  - toml=0.10.2
  - pytorch=2.4.1
  - tqdm=4.66.5
  - numpy=1.24.4
  - pandas=2.0.3
  - joblib=1.4.2
