[WDX4_rna004_v1_0]
num_bcs = 4
SQK = "RNA004"
spc = "rna004_130bps@v1.0"
which_barcodes = [3, 4, 5, 7]

[WDX4b_rna004_v1_0]
num_bcs = 4
SQK = "RNA004"
spc = "rna004_130bps@v1.0"
which_barcodes = [4, 5, 7, 11]

[WDX4c_rna004_v1_0]
num_bcs = 4
SQK = "RNA004"
spc = "rna004_130bps@v1.0"
which_barcodes = [4, 5, 6, 11]

[WDX6_rna004_1_0]
num_bcs = 6
SQK = "RNA004"
spc = "rna004_130bps@v1.0"
which_barcodes = [4, 5, 6, 7, 11, 12]

[WDX10_rna004_v1_0]
num_bcs = 10
SQK = "RNA004"
spc = "rna004_130bps@v1.0"

[WDX4_tRNA_rna004_v1_0]
num_bcs = 4
SQK = "RNA004"
spc = "rna004_130bps@v1.0_tRNA"
which_barcodes = [3, 4, 5, 7]

[WDX4b_tRNA_rna004_v1_0]
num_bcs = 4
SQK = "RNA004"
spc = "rna004_130bps@v1.0_tRNA"
which_barcodes = [4, 5, 7, 11]