[core]
max_obs_trace = 15000

[sig_extract]
padding = 100
normalization = "none"

[segmentation]
min_obs_per_base = 15
running_stat_width = 30
num_events = 110
normalization = "mean"
barcode_num_events = 25
accept_less_cpts = false

[mvs_polya]
mvs_detect_check = true

[cnn_boundaries]
cnn_detect = false

[llr_boundaries]
llr_detect = true
